export { getMovies } from "./list"
export { getMaxMinWinIntervalForProducers } from "./maxMinWinIntervalForProducers"
export { getStudiosWithWinCount } from "./studiosWithWinCount"
export { getWinnersByYear } from "./winnersByYear"
export { getYearsWithMultipleWinners } from "./yearsWithMultipleWinners"
